### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#1]
Current statements on scope and audience:

- > The official images and images by established organisations should be your preferred source of snippets if you craft your own Dockerfile. Automated builds can be164complex to set up, and details are out of scope of this article.
- > Research Software Engineers (RSEs) are not the target audience for this work, but ...
- > The goal of this article is to guide you to write a Dockerfile so that it best facilitates interactive development and computer-based research, as well as the higher goals of reproducibility and preservation of knowledge.

-------

Original notes

- not a single word about `docker run` ? > unrealistic and incomplete
- if authors already have a package structure, e.g. R or PyPI, are they out of scope?
- examples from which languages are helpful/relevant?
  - R - yes
  - Python - yes
  - (Daniel) IMO the above cover 80% of the addressed researchers
  - Julia?
  - Octave?
  - Java?
  - Perl?
  - Scala?
  - [LibreOffice calc in headless mode](https://superuser.com/questions/1135850/how-do-i-run-a-libreoffice-macro-from-the-command-line-without-the-gui) - in scope??

**Comment by nuest** [comment]
The scope is alright now, at least in the statement, BUT the content is probably going beyond what is feasible for the audience.

**Comment by vsoch** [comment]
I don't understand what the action item is here?

**Comment by nuest** [comment]
No current action item, more a reminder for us that when we re-read the current full draft, we should evaluate each rule with the scope and audience in mind.

**Comment by nuest** [comment]
Thanks to work by @vsoch @sje30 and partly myself, the scope is properly described now, including a distinction from related work, see #49
