### ISSUE TITLE
Discussion - Rule 6. Capture environment metadata

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#13]
This would perhaps benefit from a best suggested practice example?

How does this relate to Rule 8 (End the `Dockerfile` with build and run commands)?

Also:

- conventions for naming and tagging images built from a Dockerfile that can be called on from other Dockerfiles? 
- in practice, there may also be issues regarding naming containers run from images, particularly when it comes to managing linked data volumes attached to containers that are perhaps started, stopped and restarted; or started, stop, deleted, and started *de novo*.

The "environment" word also makes me think of `ENV` and `ARG` variables. eg my example use case for this is [On Not Faffing Around With Jupyter Notebook Docker Container Auth Tokens](https://blog.ouseful.info/2019/02/05/on-not-faffing-around-with-jupyter-docker-container-auth-tokens/).

**Comment by nuest** [comment]
Image tagging is by now discussed a little bit.

Naming containers is out of scope, I think.
