### ISSUE TITLE
Good Points

### ISSUE THREAD

**Issue by vsoch** [nuest/ten-simple-rules-dockerfiles#22]
https://offby2.com/posts/001-docker-lesser-known-tips/

**Comment by nuest** [comment]
@vsoch I'd add an example for using `org.opencontainers..` labels.

_What other concrete points would you include?_ About Docker Sockets/priviledged or about `root` user? Would you say we should recommend to add a `USER 1000` towards the end of the Dockerfile? Or is it only about pointing out the potential pitfalls?

IMO the following topics from the linked article are not relevant for this manuscript: heathcheck, integration testing speed, Docker API, SSH key mounting.

By now I'm sure we will have to "kill some of our darlings" to make the rules "simple" again...

**Comment by psychemedia** [comment]
At some point, this spills into good practice about building environments in terms of setting user roles and permissions appropriately, eg rather than just installing and running everything as root because that's easiest...

I think there are also gotchas with some build tools; eg if you use `repo2docker` on your local machine, doesn't it create the user you called repo2docker with on host inside the container?

**Comment by vsoch** [comment]
Based on all of your backgrounds, I think the paper should likely be scoped to data scientists, and data scientists aren't going to think about those more hpc / software engineer oriented things.

**Comment by nuest** [comment]
@vsoch Can you take a stab at this, or see what the main points from the linked blog post are that are worth including?

**Comment by vsoch** [comment]
I think the points are good, but that they are possibly too advanced for data scientists. I'll detail each point, and add comment about why I think this is the case:

 - don't run containers as root: _most_ data science (and even non data science containers) maintain root as the default user. It gets a lot more complicated to build a container without being the root user. For the most part, the security issues are addressed when a docker container is converted to singularity (and the user runs as him or herself).
 - make use of capabilities: _definitely_ out of scope for data scientists.
 - implication of access to sockets: ditto
 - don't mount ssh keys: this is the only one that might be relevant for data scientists, because it is sort of a hack shown around for various data science blogs / examples. But I do think it would be advanced and probably not appropriate for the paper, given the feedback you've received.
 - label your docker images: we totally cover this :)
 - speed up integration testing: would be more appropriate for a paper on testing containers, along with any other kind of optimization thing.
 - leverage docker architecture: also too advanced
 - healthcheck: this could be added as a single line when we talk (somewhere?) about testing containers, but honestly I've never used it. It seems to me like it should be handled by some third party (e.g., the cloud service you are running). But if you do want to add it, do something like:

> If your container is running a service or application that warrants testing, you can use the `HEALTHCHECK` prefix in the Dockerfile to specify a command to run that is expected to exit on success (with return code 0). For example, the command below will instruct Docker to check the health of the local webserver every minute.

```bash
HEALTHCHECK --interval=1m \
            --timeout=5s  \
            --retries=3   \
            curl -f http://localhost/ping || exit 1
```

**Comment by nuest** [comment]
I agree with @vsoch's very detailed analysis: if we want to explain these points, we have to broaden the scope, which we should avoid.
