### ISSUE TITLE
Reusing / extending a Dockerfile

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#28]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L86

This is more about direct reuse than using something to help you *generate* a new Dockerfile? To me, *generation* is more akin to something like https://github.com/RobInLabUJI/ROSLab, a tool for generating Dockerfiles from a form driven app.

**Comment by vsoch** [comment]
If a container exists that does exactly what you need (e.g., nginx or postgres) then you don't need to roll your own. That's different from using a tool to do a custom build. I would say the general algorithm is:

 - determine if a container already exists, If yes, you're done.
 - if no, determine if there is a tool that can help you to generate a custom container using best practices. If yes, use it. 
 - If no, find the base container that is well maintained and strongly helps with your use case. Use it. You don't have any choice but to write / customize the Dockerfile (off of the base container) at this point. Make sure you take the time to set up testing, automated build and deploy, etc.
 - And the step that wouldn't be mentioned in a paper - make the missing tool, or interact with a community that makes container tools to suggest it.

**Comment by psychemedia** [comment]
Re:

- determine if a container already exists, If yes, you're done.
- if no, determine if there is a tool that can help you to generate a custom container using best practices. If yes, use it.

I think there are several other options:

- take an existing Dockerfile that *almost* does what you want, and fork / modify that; (you may even want to go back to the original maintainer if your change generalises theirs, eg by using a parameter rather than a literal somewhere, or that picks up on a pinned version that may not be the version you want);
- take a chunk out of a pre-existing Dockerfile that does what you want (eg installing a particular application);
- still a *pattern* from another Dockerfile, eg multistage builds may be hard to make sense of from the docs, but you may be able to learn from a usecase in another Dockerfile how to achieve a similar effect in your own.

Re: tools to generate custom containers: I'm guessing this may fall into general purpose tools and tools that are targeted towards particular topics / domains / sorts of build.

If there are build tools, then they are likely to either reuse existing snippets or generate files according to rules, in which case: knowing those rules (as in the case of knowing rules used by linters) can inform your own practice.

**Comment by vsoch** [comment]
Yeah I think that's done in practice, but since we are advocating for some "better" practice, that sort of goes against the entire first point to _not_ write a Dockerfile, if you can help it. It is really just more detail into the third point that I gave - that if the thing doesn't exist, try to create it using lines that have already been tested / possibly work well.

**Comment by nuest** [comment]
@vsoch @psychemedia I think we have the topics discussed here covered in the current draft, i.e. the step-wise process of Rule 1, and we also make clear who to build on (trust to build on) with your own Dockerfiles. Feel free to re-open!
