### ISSUE TITLE
"configure an automated build"

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#31]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L123

This reads a bit along the lines of *"__just__ configure an automated build"*, which is a whole load of other skills about which folk are not necessarily aware.

As `repo2docker` has already been mentioned, it may be worth finding, or writing, something elsewhere that could be referenced showing how repo2docker can be used as part of an automated build and push system in Github ([example](https://github.com/TrackingJupyter/archive/blob/master/TJ24.md#continuous-integration-and-automated-builds)).

**Comment by vsoch** [comment]
That would be a good idea! And you are correct, automated builds aren't always easy. I've found that Circle orbs an accomplish this in relatively few lines of yaml. https://circleci.com/orbs/registry/orb/circleci/docker#commands-build 

There are also a lot of nice GitHub workflows for build / deploy that are easily added to the repo, and then they just run. https://github.com/actions/starter-workflows/tree/master/ci
