### ISSUE TITLE
Formatting Dockerfiles

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#33]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L154

One way of conforming to style when writing a Dockerfile is to use a linter; there are several around (eg [here](https://github.com/hadolint/hadolint), [here](https://github.com/projectatomic/dockerfile_lint), and "officially" in VSCode [here](https://github.com/microsoft/vscode-docker)).

But who sets the rules? Is this one way a community can start to recommend and police convention, by requiring Dockerfiles are linted before they can be shared?

**Comment by nuest** [comment]
Duplicate of #5 - @psychemedia are you alright with moving the discussion there?

**Comment by psychemedia** [comment]
Yes, sure, apols.. My commenting was stream-of-consciousness as I read through the latest version...
