### ISSUE TITLE
"try to design the `RUN` statements"

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#34]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L205

This also speaks to optimisation of an each; each statement generates a layer in the container, so to build efficient images you may want to have some quite convoluted `RUN` statements. Good layout, and convention in writing individual `RUN` lines, can help here.

**Comment by nuest** [comment]
Are convoluted `RUN` statements always bad from your point of view?

Can you check the current draft for specific missing conventions and layout tips that you'd like to add?
