### ISSUE TITLE
"small data files and software that is essential for the function of a container"

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#37]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L287

Earlier it was mentioned how it can be useful to add instructions into the Dockerfile that document examples of how to actually build the container.

It can also make sense to include simple demos of how to use the environment that has been built. Such demos also often play the role of "human operated tests" — when you've built your image, does your demo file work correctly? (Another way of working out how to use whatever is in  in a container is to look for any test files, and poke through them..)

Continuous build has been mentioned elsewhere. For this to be most valuable, the build system should also be able to run a test to check the build has built something that works as expected, not just that the build has run to completion without error.

**Comment by vsoch** [comment]
@psychemedia just a thought - instead of opening issues, why not just open a PR with all your suggested changes, and then you'll actually get credit (via the lines / commit) for your ideas, and it skips the step of someone else needing to take the issues you are opening here and writing them for you (and then you also not getting credit for some of the ideas). Just a thought :)

**Comment by psychemedia** [comment]
I'm pushed for time and just making discussion notes on a quick read through of the whole doc...

Will try to revisit some of issues and make PRs...

**Comment by nuest** [comment]
I think the original concern is covered in the current text version.

As for the process: I'm trying to take care of things as best as I can, even throwing in the occasional ["Co-authored-by"](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors), but am grateful for any PR.
