### ISSUE TITLE
"you should consider switching tools"

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#40]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L353

Switch tools to what? And why?

Containers are lightweight VMs and can be used to share desktops via a browser using things like novnc; XPRA, RDP etc also provide other ways of accessing the GUI element, which may be the primary, indeed the only, way of using whatever's inside the container?

**Comment by vsoch** [comment]
VMs are fine and dandy, but you aren't going to easily automate building and testing. If someone has a workflow they want to broadly share, it's much easier to have a container. This is my opinion, and you are free to disagree.

**Comment by nuest** [comment]
I think this point is independent from VMs or containers, but about the _scientific workflow_. I think we have very well documented the possibilities for containers that provide a "headfull" execution via various user interfaces.

@vsoch I totally agree with you about VMs, but AFAICS the argument is more about the actual workflow than the method to capture the computing environment.

I've tried to clarify this in https://github.com/nuest/ten-simple-rules-dockerfiles/commit/e7179329e2db640e4db5502b85628694cfa6226f
