### ISSUE TITLE
"the harder it will become"

### ISSUE THREAD

**Issue by psychemedia** [nuest/ten-simple-rules-dockerfiles#43]
https://github.com/nuest/ten-simple-rules-dockerfiles/blob/4a87e3e3ad43feacd98722f1521e500191bb17bb/ten-simple-rules-dockerfiles.Rmd#L400

Is the point here that it will actually become harder to identify and fix whatever it is that is breaking a build? That if you rebuild regularly, you maximise the likelihood that you only need to identify and fix a small number of easily detected errors? Rather than waiting for months and being presented with all manner of things that are inter-dependent or that may break other things in other ways as you try to fix them?

**Comment by vsoch** [comment]
If change happens consistently over time, the longer you wait, the more change, and the more potential that your previous working build won't work. Think of Tensorflow - you can build a container with whatever version exists today, and if you try to rebuild next year, you are hugely likely to run into issues. Doing regular builds (along with making sure security / vuln fixes go in) allows you to more incrementally debug that.
