### ISSUE TITLE
ContainDS

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#50]
https://containds.com/

https://twitter.com/danlester/status/1216686349832589312

**Comment by psychemedia** [comment]
I've been playing with this... It's really useful, like having your own personal persistent BinderHub.

Derived from Kitematic, it lets you:

- launch a Jupyter container from eg Jupyter docker stack, with a single click (the token etc is handled for you so the notebook page just opens in the browser);
- build a container from a local dir or a github repo, as per MyBinder, using repo2docker (which I think runs itself from a docker container, so no install required? I need to check that...)
- take snapshots / clones of an image and give then a new image name
- export containers as a standalone file (albeit a large one!) that can be shared with others and loaded in using containds.

One workflow I'm exploring (eg [WIP here](https://github.com/innovationOUtside/tm129-robotics2020) uses a Github action to build a container from releases in the repo using repo2docker and then push it to dockerhub, and then distribute the image to others via dockerhub loaded through containds.

**Comment by vsoch** [comment]
It seems cool, but using a Linux OS, I'm sort of left out from the club :/

**Comment by vsoch** [comment]
Is there another link to the tweet? That one doesn't work for me.

**Comment by nuest** [comment]
Linux seems to be in low demand so far, but according to Dan on Twitter it's possible.

Re. the tweet link: The tweet announced the file export feature, see https://containds.com/2020/01/10/export-container-as-a-file-to-share-with-others-0-2-5/ and https://containds.com/docs/reference/containds-file-format/

**Comment by psychemedia** [comment]
@vsoch I was chatting to Dan about that. Kitematic ships to Linux, so is there likely a path to distributing for Linux. But packaged how / for which Linux was one question. A second was: Linux users are probably equally, if not more, comfortable using the command line where they can actually know what commands are being issued...

**Comment by vsoch** [comment]
This is true, but I'd say (generally) there are a lot of Linux users that also enjoy (at least trying) GUI applications. In the same way you can have biases in society for different kinds of people, we don't want to have those same biases for software. Unless there is compelling reason not to, I'd say generally some GUI application that is research oriented should not send an underlying message "Linux not allowed!" But I also agree, Linux users are more likely to use a command line. It's sort of like the introverted kid conundrum, we may not want to go to the birthday party, but we still want to be invited. :)

**Comment by psychemedia** [comment]
@vsoch Packaging still an issue though - which Linux / GUI app distributed how / what sort of desktop/graphical environment dependencies required etc? (eg I'm generally only a naive user of headless Linux, and then pretty much stick to ubuntu for convenience; so the consequences and requirements of packaging for "Linux" in general, and "Linux GUI apps" in general, are rather beyond my ken...;-)

**Comment by vsoch** [comment]
Usually for Linux you just provide the source to install from, but of course it totally depends on the software.

**Comment by nuest** [comment]
ContainDS is mentioned, but I wouldn't go further with this at the moment.
