### ISSUE TITLE
Preprint venue

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#51]
Let's use this issue to vote on the preprint venue, one platform per comment.
Goal is to publish the preprint end of February 2020.

The platform should support posting the PDF as it is generated now.

Use as many +1 and -1 as you like (maybe adding a comment why in the case of the latter) so we can also do a negative sorting (choose the one where least people have valid concerns).

Unfortunately, https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005473 does not have any rules about selecting a preprint server.

I did not include Zenodo (because mostly posters/software/data), and might have overlooked others - feel free to add your favourite to the list if I missed it.

**Comment by nuest** [comment]
**Don't preprint** but submit directly to PLOS - they will post a preprint on bioRxiv, see https://blogs.plos.org/plos/2018/05/power-to-the-preprint/

**Comment by nuest** [comment]
[Preprints.org](https://www.preprints.org/)

Run by MDPI, https://www.preprints.org/about, have comments, indexed well.
MDPI is seen as "almost predatory" by some...

**Comment by nuest** [comment]
[arXiv](https://arxiv.org/)

THE preprint server, but no DOI.

**Comment by nuest** [comment]
[OSF preprints](https://osf.io/preprints/)

Open platform, non-profit.

**Comment by nuest** [comment]
[bioRxiv](https://www.biorxiv.org/)

**Comment by nuest** [comment]
One comment from my side: I like the PLOS+bioRxiv collaboration, but since the article to me is somehow also a process of seeking concensus, I do like the idea of _us_ being the once who control the speed about the next steps. I'd be happy to let the preprint sit there for some time, say _one month_ (?), and see if there is any feedback.

**Comment by sje30** [comment]
my -1 for biorxiv might sound odd (esp as an affiliate editor), but I am worried this article will be rejected as it is not about results.  They do not accept reviews, and you will see many comments on twitter about biorxiv rejecting review manuscripts.  They also do not allow you to update post acceptance.

arvix is great, but sometimes the 1+ day delay in posting it seems odd.  OSF seems to be the smoothest workflow in my experience.

**Comment by vsoch** [comment]
Voted!

**Comment by nuest** [comment]
I'll break the tie here.

### We're going with OSF.

It's nice that we can include the GitHub repository, and this potentially being a topic many people are interested in, I hope the [commenting functionality](https://help.osf.io/hc/en-us/articles/360019738554-Annotate-a-Preprint) might actually be used.

Note to self: step-by-step instructions: **https://help.osf.io/hc/en-us/articles/360019930533-upload-a-preprint**

@vsoch @benmarwick @sje30 @betatim @psychemedia Please post your OSF profile links here or send them to me in some way - thanks!

**Comment by vsoch** [comment]
I had forgotten that I even had a profile on here! Here you go: https://osf.io/7zk9q/

**Comment by benmarwick** [comment]
My OSF profile is https://osf.io/xh5qn/

**Comment by sje30** [comment]
https://osf.io/tgm2a/

thanks Daniel.  Will be catching up this week on this paper.

**Comment by nuest** [comment]
@betatim is https://osf.io/vd2j6/

**Comment by nuest** [comment]
@psychemedia Do you have an account on OSF yet?

**Comment by psychemedia** [comment]
@nuest Newly minted OSF account here: https://osf.io/ntz2e/ but it's bare bones...

**Comment by nuest** [comment]
https://doi.org/10.31219/osf.io/fsd7t (may take up to 24 hours)

https://osf.io/fsd7t
