### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#53]
@vsoch @benmarwick @sje30 @betatim @psychemedia Please add any funding etc. you need to the acknowledgements section.

**Comment by betatim** [comment]
Nothing from my side.

**Comment by vsoch** [comment]
Nothing from me!

**Comment by vsoch** [comment]
I already responded, so I'm removing the assignment, thanks @nuest !

**Comment by sje30** [comment]
done.
