### ISSUE TITLE
Invite feedback

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#56]
- [x] open a feedback issue, including the planned _submission date_

## Ping people

- @nuest
  - [x] Sam Abbott: https://github.com/nuest/ten-simple-rules-dockerfiles/issues/6#issuecomment-595125323
  - [x] Noam Ross, potentially via _"Make tends to be my highest-level abstraction - for things like building dependencies, docker images, etc. I've started using drake for analysis pipeline below that."_ (https://twitter.com/noamross/status/1205514611912531968?s=09)
  - [x] reply to https://twitter.com/nordholmen/status/1164446676427431936
  - [x] as Dav Clark (Gigantum), their tool focusses on UI, but still
  - [x]  `#containers` in RSE Slack - "many of you must help researchers with containerisation - maybe this is of help for you or you can share your experiences"
  - [x] https://twitter.com/Stikov/status/1191847797177421825?s=09)
  - [x] ping authors of https://f1000research.com/articles/7-742/v2
  - [x] Fotis E. Psomopoulos, https://twitter.com/fopsom

**Comment by nuest** [comment]
https://github.com/nuest/ten-simple-rules-dockerfiles/issues/61

**Comment by nuest** [comment]
@sje30 Do you know Pablo Moreno from EBML Cambridge? He's coauthor of the F1000 paper..

**Comment by sje30** [comment]
No, I don't know Pablo (yet).

**Comment by nuest** [comment]
@sje30 Yes, please point them to our preprint! It would only be fair to point out we plan to submit soon.
