### ISSUE TITLE
Coauthors | Coordination

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#6]
@betatim @sje30 @benmarwick

I would really enjoy to move this idea along during the next couple of months, maybe have a first version ready by the end of the year. _Does that work for you (if you're in) ?_

IMO: we're open to more views and coauthors, so feel free to suggest potential collaborators. Reaching a broader "consensus" will be harder, but only make the rules stronger :muscle: !

**Comment by nuest** [comment]
It would be great to get some more eyes on this. Ideally I'd like to get a few more people on board and then have a call beginning of November to discuss the contents and how to share the writing tasks.

**Comment by nuest** [comment]
And if you're joining, don't forget to to add yourself to the list of coauthors and outline what you'd like to do in the contributions section.

**Comment by sje30** [comment]
Laurent, @lgatto would you like to join this project to write tips for Docker?

**Comment by lgatto** [comment]
Very interesting - I would love to join, thanks! Let me read it and see if there's anything I can contribute.

**Comment by nuest** [comment]
@lgatto Thanks for your interest! At the moment you opinion on the current rules would be very helpful before turning the bullet points into text. You could also add some examples you know to #4.

**Comment by nuest** [comment]
Also pinged @vsoch and @psychemedia via email, who could provide new insights from Singularity and education respectively (and probably other perspectives!). _Looking forward to hear your opinions!_

**Comment by nuest** [comment]
@simonw Hi there! @psychemedia suggested you might be interested in this topic. Would you be interested to share your experience of writing Dockerfiles in a research context?

**Comment by nuest** [comment]
The manuscript get's longer and longer, and the discussions here in the repo are quite diverse and challenging. I'm learning a lot!

@sje30 @betatim Would you have time to give the article a full read some time next week? I'll try to work though the majority of open issues until then (help welcome, there are soo many good points and ideas in there like [this one](https://github.com/nuest/ten-simple-rules-dockerfiles/issues/44#issuecomment-562697379)).

@lgatto Did you find a section you'd like to work on?

@benmarwick Would you be interested to join in, by giving feedback on the overall layout of rules, or even specific content in the rules?

------

**Remaining work**: I'll work on the open issues and discussion points during the next couple of weeks, but welcome any help. Especially useful right now would be contributions on the following points:

1. **Scope**: the rules should focus on reproducible computing environments in scholarly communication.
3. **Examples**: if we see a value in a collection of examples, it should be substantial, see #4 
2. **Simplicity**: we've put in a lot of experience and knowledge into the rules (thanks especially to @vsoch for making the first full text draft out of partly random bullet points!), which IMO resulted in some of them not being that "simple" anymore and need focusing - related to _scope_. We can also re-visit content that goes to far beyond `Dockerfile`s into how to run containers etc (e.g. should we mention `docker push`? > #15).

To avoid double work, please work in a branch/fork and open a work-in-progress PR so we have the current state captured. If you (or me) push to `master`, which is fine for small fixes, at an untimely hour then you are responsible for resolving the conflicts :-). Thanks for your understanding!

------

I'd like to schedule a **call for all contributors** some time in January to flesh out the remaining bits so we can put this on a preprint server and get feedback from the broader community **by end of January 2020.** Please fill in your availability: https://terminplaner4.dfn.de/zlg7jwppxfYiGn6E ([timezones](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20200106&p1=37&p2=136&p3=137))

**Comment by vsoch** [comment]
You got it @nuest ! One comment about scope, instead of:

> the rules should focus on reproducible computing environments in scholarly communication.

I'd directly mention data science. 

> the rules should focus on reproducible computing environments for data scientists' work.

The reason is because it's also common to publish papers that detail containers used for infrastructure or similar, and the first statement above would include those (while the paper largely does / or will not)

**Comment by betatim** [comment]
@nuest I will be offline till early January starting tomorrow so won't be able to read the paper :(

**Comment by nuest** [comment]
@betatim Thanks for the head up - and no worries, your inputs will still be helpful in January! It would be great if you could fill in your availability for the telco before you go. Thanks!

**Comment by sje30** [comment]
I'll take a read in the next few days, I'm amazed at the volume of discussion!  this is great.

**Comment by nuest** [comment]
@sje30 @betatim @vsoch @benmarwick @lgatto @psychemedia 

Hi all! _I'll pick up the ball on this next week._ I hope you understand that sometimes our scheduling goes awry, and this time it was _mine_. :pray: sorry!

I'll start by resolving the open PRs and will announce here when a new iteration based on [these ideas](https://github.com/nuest/ten-simple-rules-dockerfiles/issues/6#issuecomment-564303990) is ready. _What can you do in the meantime?_

**@all**: Vote on #51 

@betatim @sje30 You're even more busy than I am (most of the time ;-) ), so could you schedule a few consecutive hours in the last week of January to help out with a full revision of the then hopefully good looking draft?

@psychemedia you've started plenty of though-provoking issues, thank you very much for that! Would you be open to revisit them, even if nobody else replied yet, and see if you're able to turn them into concrete writing tasks?

@lgatto Did you find a section you'd like to work on?

**Comment by sje30** [comment]
yes, its on my todo list! sorry for my tardiness.

**Comment by psychemedia** [comment]
@nuest I can but try , though not sure when. One of reasons for so many issues was just to start one per rule as a locus for discussion on each rule. IIRC, some of other issues were just comments to content, which may have been addressed, essentially resolved by discussion and/or revisions.

**Comment by nuest** [comment]
@vsoch @benmarwick @sje30 @betatim @psychemedia Hi! Long time no hear!

I've tried to make a push forward with this manuscript and was able to close quite a few issues. I also assigned some of the issues to people - please comment in these issues if it is realistic that you can spend some time on them in the coming couple of weeks. _Thanks!_

**Comment by nuest** [comment]
@seabbs I've come across your instructions for replicating your research with Docker (@ others, see links below). Great efforts! We are a merry band of container users in research and are trying to put together a Ten Simple Rules - article for using Dockerfiles in science. You can read the current draft at https://nuest.github.io/ten-simple-rules-dockerfiles/ten-simple-rules-dockerfiles.pdf Would you be interested to give your feedback or contribute your experiences?

------

https://github.com/seabbs/ModelTBBCGEngland#using-docker
https://github.com/seabbs/tbinenglanddataclean#docker
https://github.com/seabbs/ExploreBCGOnOutcomes#docker

**Comment by seabbs** [comment]
Thanks for reaching out @nuest. This sounds like a great idea looking forward to reading! 

Very happy to give feedback and will contribute anything I can. I am currently working on the covid19 outbreak so my responses may be a little delayed.

**Comment by nuest** [comment]
Thanks @seabbs ! Best of luck with that work - we'll ping you when our preprint is out.

**Comment by nuest** [comment]
Hi @vsoch @benmarwick @sje30 @betatim @psychemedia !

_Hope you're all save and healthy!_

I would like to push out the article as it is now in a preprint on OSF (#51).
If someone wants to take a stab at the last issue #18 please do so, otherwise I'd revisit it before the final submission.

We should use the time we're waiting for public comments, which I would do (maybe 4 weeks?) to fill the list of examples and improve the example in the document, see #4.

_Any objections to publishing the preprint soon?_

**Comment by vsoch** [comment]
No objections from me! I think perfection is the enemy of the good, and it's good to get it out there for feedback since it could be "under development" for eternity :)

**Comment by betatim** [comment]
Sounds good to me. Thanks a lot for all the hard work.

**Comment by sje30** [comment]
Good idea.  "release early and often".

**Comment by psychemedia** [comment]
Fine by me... apols for not contributing more actively (my Docker practice tends to be "quirky" rather than "best"!).

**Comment by nuest** [comment]
@vsoch @psychemedia Last remaining open question I am aware of is in this little discussion: https://github.com/nuest/ten-simple-rules-dockerfiles/commit/ee13e359f3a15ead01e3ae3a65bb1bd60eff5fe2#r38530647 I'd be grateful for a timely PR to remedy this.

**Comment by vsoch** [comment]
In another comment you mentioned that you wouldn't wait for changes for some pre-print, so I'm confused if you want someone to jump on this or it wouldn't matter anyway... ?

**Comment by nuest** [comment]
I think this was a relevant enough issue to hold the preprint back, because it was relatively controversial. But you convinced me! See discussion on the commit linked above.

**Comment by benmarwick** [comment]
Thank you, I've had another look over the text, and I'm happy to go ahead with posting the preprint.

**Comment by nuest** [comment]
:tada: The preprint is out: :tada: **https://osf.io/fsd7t**

Here's my tweet, but please share within your networks, too: https://twitter.com/nordholmen/status/1251083470870392832

To avoid annoying people to much, we can coordinate here: #56

**Comment by nuest** [comment]
@seabbs The preprint is out now - and could use some feedback! Would be great if you can take a look!

**Comment by seabbs** [comment]
Just read through - looks really great. Looking forward to giving it a more detailed read. This is going to be incredibly useful for getting people up to speed.

**Comment by nuest** [comment]
Hi everyone @sje30 @betatim @vsoch @benmarwick @psychemedia !

Frankly, the reach on Twitter was quite overwhelming for me. I'm optimistic this translates to  useful feedback, one person already added very useful comments to the PDF on OSF. Three questions are on my mind now:

1. What is our timeline to submit the article to formal peer review?
2. Should we do a pre-submission enquiry?
3. How to build up the examples?

---------

Re 1: 4 weeks? 8 weeks?

Re 2: As I mentioned in my tweet, the rules aren't that "simple" anymore. Not precluding any ingenious editing, should we stick to the goal to submit this to the "Ten simple..." series, or remove that "restriction" (disclosure: originally suggested by Dav Clark via Email) and look for other venues? Any objections against sending a letter to the PLOS Comp Biol editors to get their take?

Re 3: If most of us add one Dockerfile per week, we'd easily have two dozen before submitting to peer review :muscle: :smiley: :point_right: :point_right: #4

**Comment by betatim** [comment]
I have an extreme opinion on 2 (and hence on 1). For me it seems like there is no way the two (or three?) reviewers can out do the comments and reach via twitter. It will however use up a lot of time and patience to deal with reviewers and their (obscure?) ideas/comments. Legitimacy is bestowed on this work by who the authors are, there is no need for the stamp of approval of a journal.

When weighing my opinion do take into account that my livelihood does not depend on the academic-credits game of citations, h-index, impact factors and publications. For me the thing that counts is getting the ideas to as many people as possible (as quickly as possible).

**Comment by vsoch** [comment]
Are you asking "should we take the time to make all the cooks in the kitchen happy (Twitter) or just submit?" I'm with @betatim - I think it would be near impossible to make everyone happy, and we should more quickly get to peer review and at least make 2-3 cooks happy. For Twitter feedback, if someone submits an actual PR or issue with very specific changes that would be the threshold that we would be able to respond to. So if people are taking the time to give meaningful feedback (doesn't look like they are? -> https://github.com/nuest/ten-simple-rules-dockerfiles/issues/61) then we can respond to that. Otherwise, let's move on with it.

Can you tell me about this "series" and how that is different from submitting it somewhere else / removing the restriction? This doesn't feel like content for a biology journal, but maybe that's just me :)

**Comment by psychemedia** [comment]
I think the Twitter feedback is most likely from practitioners, though many of shares / likes will be just folk bookmarking. The most useful feedback from Twitter would be folk complaining that a rule or recommendation is wrong, which we could then follow up. (To this extent, have a unique memorable. social media tag the for the paper would be useful.)

Feedback from academic reviewers is likely to take a slightly different form, and include comment on the logical coherence of the paper as a whole, perhaps with suggestions of another reference or two we should add (eg from the reviewer's research group...).Publications like [The Journal of Open Research Software (JORS) ](https://openresearchsoftware.metajnl.com/) might solicit useful feedback from a knowledgeable reviewer, though not perhaps from the target audience.

I'm also with @betatim in terms of motivation. Though my HoD would like me to publish, I find the overhead of academic publishing cf. micro-publications and nudges I can make personally to be not-for-me. That said, formal publications do have the benefit of: 1) third party approval; 2) persistence; 3) reasonably long form / standalone / generally readable. There is also the benefit that from being part of the formal academic published record, other people working in that tradition can use the publication/reference as a building block in their own work / critique, which can lead to improvements on the original work or valuable criticism of it.

**Comment by sje30** [comment]
I think we should work towards a submission in next four weeks.  We have the momentum now.  Re: journals, PLOS Comp Biol would be a good venue, given their ten simple tips series.  We can make a presubmission enquiry (Daniel - I'm happy to do this with you).

**Comment by sje30** [comment]
here's an example Docker file in the wild that I woul dlike to improve:

https://github.com/sje30/eglen2015/blob/master/Dockerfile

**Comment by nuest** [comment]
@sje30 It would be very helpful to do the presubmission inquiry together. Should I draft an email?

@betatim I'm still playing the game and would like to try to publish the article in a peer-reviewed journal. Given the topic, I hope to come up against reviewers with experiences in Open X and to largely avoid "reviewer 2"-style comments.

@vsoch Good points regarding the level of feedback we should (not) react to. I agree! **Re. the series** see https://collections.plos.org/ten-simple-rules and https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003858

@psychemedia I like JORS as a second potential venue! Do you have a suggestion for the hash tag? `#datasciencedockerfiles` ? `#tensimpledocker` ?

**Comment by nuest** [comment]
**FYI:** This manuscript as the great advantage of several native speakers as coauthors, but also the disadvantage that we try to introduce a topic we know a lot more about than the readers do. Therefore I have send a request to my university's scientific writing support service for an editorial review. This can fix the little mistakes even several careful reading sessions by us will go over :-), and hopefully helps to clarify the language in some places.

**Comment by sje30** [comment]
Sounds like a great service!

**Comment by psychemedia** [comment]
How about #datascidockerfiles?

**Comment by nuest** [comment]
Suggested timeline for submission: **End of May**.

**Comment by nuest** [comment]
In case someone needs some motivation: IMO everyone contributing a few before/after examples - see #4 - would earn the ["Validation" role](https://casrai.org/credit/).

**Comment by nuest** [comment]
@sje30 manuscript is ready for you. Ping!

**Comment by bdevans** [comment]
We can probably close this now too. 

Maybe the shorter `#datascidocker` hashtag would be a better use of the tweet character limit?

**Comment by bdevans** [comment]
Closing since the publication is in press.
