### ISSUE TITLE
Preprint feedback

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#61]
_What do you think about the Ten Simple Rules we came up with?_

------

Update: Preprint DOI is now active :point_right: **https://doi.org/10.31219/osf.io/fsd7t** :point_left: is now active.

**Comment by dpshelio** [comment]
Link to the [preprint](https://osf.io/fsd7t/).

**Comment by nuest** [comment]
This issue can stay open for people not wanting to use Hypothesis on the preprint, but there is no task to do right now as we prepare the manuscript for submission.

**Comment by bdevans** [comment]
Time to close this?

**Comment by bdevans** [comment]
Closing this as the publication is now in press.
