### ISSUE TITLE
Missing reference in Rule 9

### ISSUE THREAD

**Issue by bdevans** [nuest/ten-simple-rules-dockerfiles#66]
In the final paragraph of Rule 9, we have the following missing reference:

> As an example, cookie cutter templates [59], project starter kits **[REF]**, or community templates (e.g., [60]) can provide required files, e.g., for documentation, CI, and licenses, and structure for getting started.

**Comment by nuest** [comment]
AFAICS this was added by @vsoch in https://github.com/nuest/ten-simple-rules-dockerfiles/commit/b1298cb9b35050357cffc8ff9bcefffe613d95c5 BUT I don't find anything fitting, except

https://github.com/project-starter-kits

which is not a useful reference.

@vsoch I'll remove this, feel free to re-add with a reference if you have a specific project in mind.
