### ISSUE TITLE
Deprecated label schema

### ISSUE THREAD

**Issue by bdevans** [nuest/ten-simple-rules-dockerfiles#67]
In Rule 4 there are examples of using labels for adding metadata. These examples use the `org.label-schema-specification` which is then noted as being deprecated. Wouldn't it be more appropriate to use the currently recommended schema?

**Comment by vsoch** [comment]
The problem is that although there is the deprecation notice, it's still hugely used - people will see labels with that convention very commonly out in the wild. So I think our strategy would best be to mention this, but then point to the now suggested convention (OCI).

**Comment by bdevans** [comment]
Since this paper represents a fresh opportunity to encourage best practices going forward (and may be reaching readers who haven't really used labels before), wouldn't it be better to give all the examples in the new recommended (OCI) format with a note to make readers aware? Something along the lines of: 
> You may also commonly find labels in the deprecated `org.label-schema-specification` format e.g., ... However we encourage the use of the new OCI schema in all new and unlabelled projects. 

There are still plenty of instances of `from __future__ import print_function` in the wild but I wouldn't give examples in Python 2 for a modern "Ten simple rules for Python Programming" type paper.

**Comment by vsoch** [comment]
That would work for me, for sure.
