### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#69]
- [x] author contributions are checked by all
- [x] acknowledgements are completed by all authors
- [x] affiliation/ORCID etc. are correct

**Comment by nuest** [comment]
@sje30 Since we make a new submission, should do it to become corresponding author?

It would of course be welcome if you can help out with a cover letter again.

**Comment by vsoch** [comment]
@nuest I'm not familiar with CRediT, what do you  need me to do?

**Comment by nuest** [comment]
@vsoch You have taken a look at the contribution section, and already fixed the roles, so you're good.

**Comment by nuest** [comment]
## Timeline

Let's target Wed May 20 as a deadline for the visual summary and changes to the text. Then, everyone will have one week to take another look at the full draft to comply with the authorship requirements and I will submit on May 29.

**Comment by nuest** [comment]
# Author contributions

"I have checked and approve the assigned roles in the author contributions", see https://github.com/nuest/ten-simple-rules-dockerfiles/blob/master/ten-simple-rules-dockerfiles.Rmd#L827

- [ ] @vsoch 
- [ ] @nuest 
- [ ] @sje30 
- [ ] @betatim 
- [ ] @psychemedia 
- [ ] @benmarwick 
- [ ] @bdevans

**Comment by sje30** [comment]
Deadline looks good to me.

**Comment by nuest** [comment]
# Author contributions

"I have checked and approve the contents of the final revision of the article", see [`Version 4`](https://github.com/nuest/ten-simple-rules-dockerfiles/tree/preprint.v4) of preprint at https://osf.io/fsd7t/

(The only expected change before submission: visual summary figure by @bdevans.)

- [ ] @vsoch 
- [ ] @sje30 
- [ ] @betatim 
- [ ] @psychemedia 
- [ ] @benmarwick 
- [ ] @bdevans 
- [ ] @nuest

**Comment by bdevans** [comment]
Hi @nuest, I've checked off my name above in anticipation of merging PR #86. These will hopefully be the final changes before submission! 🥳

**Comment by sje30** [comment]
@bdevans thanks for joining this paper, this is an excellent example of open collaboration!

**Comment by bdevans** [comment]
It's been a pleasure @sje30 - thanks to all for including me! 😊

**Comment by nuest** [comment]
@psychemedia friendly ping! I hope you find the time to give the text another read, because there were significant changes since we've last conversed on the paper, and I still found a few small mistakes this morning.

**Comment by psychemedia** [comment]
@nuest APols for tardiness; I've ticked off required checkboxes and made some minor language change suggestions in branch `th-final-comments` if you want to cherry pick any of them.

**Comment by bdevans** [comment]
They look like good edits to me @psychemedia - would you like to submit them as a PR so that they can be merged into the main repo?

**Comment by nuest** [comment]
**Thanks everyone!** I'll keep you posted on the next steps.

**Comment by nuest** [comment]
Preprint updated base on [the Travis CI rendering](https://nuest.github.io/ten-simple-rules-dockerfiles/ten-simple-rules-dockerfiles.pdf), now at version `5`: https://osf.io/download/5e9964fbf135350557d5a298/?version=5&displayName=ten-simple-rules-dockerfiles-2020-06-16T10%3A28%3A50.369Z.pdf

**Comment by nuest** [comment]
![image](https://user-images.githubusercontent.com/1325054/84770405-cd92c980-afd7-11ea-8479-860f6e6c0c86.png)
