### ISSUE TITLE
Improve and clarify bind mounts vs. volumes

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#77]
- data should remain bind mounted
- volumes can be used for persisting changes within the image > they should be discouraged for reproducible data science
- all changes should be under version control in the repo where the Dockerfile is
- volume mounts would be faster if e.g. a _fast_ database connection is needed
- mention volume only in rule about ordering, so users are aware of the implications
- only (large) data files should be mounted, unless an IDE container is used (Jupyter)

**Comment by nuest** [comment]
@bdevans All bullet covered covered, except the one about the IDE container, right? Since that aspect would complicate the rules, I will follow your decision if you prefer not to cover it.

**Comment by bdevans** [comment]
Hi @nuest, that point is covered in the following under the current Rule 9 (One Docker & use VCS):

> If you prefer to edit your scripts more interactively in a running container (e.g., using Jupyter) then it may be more convenient to bind mount their directory from the host at run time, provided all changes are commited before sharing. 

Does that suffice? If not we could repeat the point elsewhere.
